<a href="https://colab.research.google.com/github/ucfilho/Disciplina_Metodos_Numericos_2020/blob/master/Aula_05_Met_Matematicos_set_08_2020.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [2]:
A = np.array([[0.9 ,0.3 ,0.1] ,[0.1 ,0.5 ,0.2] , [0.0 ,0.2 ,0.7]])
b = np.array([30.0 ,25.0 ,10.0])

In [3]:
#  GAUSS SIDEL CONVERGE
# A is symmetric positive-definite --->positive definite if and only if all of its eigenvalues are positive.
# A is strictly or irreducibly diagonally dominant

In [4]:
eigenvalues,eigenvectors =np.linalg.eig(A)

In [5]:
print(eigenvalues)

[0.34384472 1.         0.75615528]


In [6]:
print(eigenvectors)

[[-0.35708982 -0.95025527 -0.77669562]
 [ 0.81444203 -0.25916053  0.17027001]
 [-0.45735221 -0.17277369  0.60642562]]


In [7]:
def Verifica_diagonal_dominante(X):
  D = np.diag(np.abs(X)) # Find diagonal coefficients
  S = np.sum(np.abs(X), axis=1) - D # Find row sum without diagonal
  if np.all(D > S):
    STATUS='matrix is diagonally dominant'
  else:
    STATUS='NOT diagonally dominant'
  return STATUS

Verifica=Verifica_diagonal_dominante(A)
print(Verifica)

matrix is diagonally dominant
